#!/bin/bash
# Need classpath to be explicitly mentioned to include required jar files
  chmod u+x 3700ftp
# Invoking the entrypoint file mainfile
# $@ represents all the command-line arguments passed to the script when it is executed.
  java Main "$@"